### ISSUE TITLE
The property ... has unknown type

### ISSUE THREAD

**Issue by mauriciolima88** [PKGeorgiev/Delphi-JsonToDelphiClass#7]
When the file starts as:

{
  "html_attributions": [],
  "next_page_token": ...

it shows the message: The property [html_attributions] has unknown type.

**Comment by PKGeorgiev** [comment]
That's right. Json2delphi class needs arrays to have at least one element to determine Array's type (it converts arrays to `Array<T>` where T is the type and must be known before conversion).
As a workaround if you know Array element's type, just add one fake element to it, for example:

```
{
"html_attributions": ["fake_element"],
"next_page_token": ...
}
```
In this case html_attributions will be converted to `Array<string>`. Hope that helps.

**Comment by mauriciolima88** [comment]
Alright, I'm going to make a simple stringReplace on Json, thank you very
much!

2017-11-26 19:28 GMT-02:00 PKGeorgiev <notifications@github.com>:

**Comment by PKGeorgiev** [comment]
Glad to help you!
